name: Generate PDF with Pandoc

on:
  push:
    branches: ["main"]
    paths:
      - "README.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: pandoc/latex:latest
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert README to PDF
        run: |
          pandoc README.md \
            -o CV_Jose_Vallejos.pdf \
            --pdf-engine=xelatex \
            -V geometry:margin=1in

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: curriculum-vitae-pandoc
          path: CV_Jose_Vallejos.pdf

      - name: Install git
        run: apk add --no-cache git

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push PDF
        run: |
          git add CV_Jose_Vallejos.pdf
          git commit -m "Update CV PDF" || echo "No changes to commit"
          git push
