name: Generate PDF with Pandoc

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:latest # Imagen oficial con todo lo necesario
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert README to PDF
        run: |
          # Convierte el Markdown a PDF usando un engine de LaTeX
          pandoc README.md -o CV_Jose_Vallejos.pdf --pdf-engine=xelatex -V geometry:margin=1in

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: curriculum-vitae-pandoc
          path: CV_Jose_Vallejos.pdf
